### ISSUE TITLE
Error with segments = FALSE

### ISSUE THREAD

**Issue by artemklevtsov** [andrie/ggdendro#13]
Hi.

```r
library(ggdendro)
hc <- hclust(dist(USArrests), "ave")
ggdendrogram(hc, rotate=FALSE, segments = FALSE)
#> Error: No layers in plot
```

**Comment by andrie** [comment]
Thanks for the error report.  Do you have any suggestions on what the desired behaviour should be?

**Comment by unikum** [comment]
I don't clear what this option should do. Anyway it doesn't work. `geom_segment` is main layer of the plot. The `segments=FALSE` blocks plotting,

Also I don't see where used `label` arg. `leaf_labels` provides `geom_text` layer.

Last:

```r
    if (rotate) {
        p <- p + scale_x_discrete(labels = data$labels$label)
    }
    else {
        p <- p + scale_x_discrete(labels = data$labels$label)
    }
```

equal actions in both cases.

**Comment by andrie** [comment]
Fixed this by adding `geom_blank()` to plot.
