### ISSUE TITLE
Examples, vignettes and tests fail if tree is not installed

### ISSUE THREAD

**Issue by hadley** [andrie/ggdendro#16]
```
checking examples ... ERROR
Running examples in ‘ggdendro-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: dendro_data.tree
> ### Title: Extract data from regression tree object for plotting using
> ###   ggplot.
> ### Aliases: dendro_data.tree
> 
> ### ** Examples
> 
> require(tree)
Loading required package: tree
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘tree’
> require(ggplot2)
Loading required package: ggplot2
> require(MASS)
Loading required package: MASS
> data(cpus, package="MASS")
> cpus.ltr <- tree(log10(perf) ~ syct+mmin+mmax+cach+chmin+chmax, cpus)
Error: could not find function "tree"
Execution halted
```
```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  'help.start()' for an HTML browser interface to help.
  Type 'q()' to quit R.
  
  > if(require(testthat)) test_check("ggdendro")
  Loading required package: testthat
  Loading required package: ggdendro
  Loading required package: tree
  Error in eval(expr, envir, enclos) : could not find function "tree"
  Calls: test_check ... test_dir -> lapply -> FUN -> sys.source2 -> eval -> eval
  In addition: Warning message:
  In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
    there is no package called 'tree'
  Execution halted
```
```
checking re-building of vignette outputs ... NOTE
Error in re-building vignettes:
  ...
Quitting from lines 93-107 (ggdendro.Rmd) 
Error: processing vignette 'ggdendro.Rmd' failed with diagnostics:
could not find function "tree"
Execution halted

```

**Comment by andrie** [comment]
Although I think the package as it stands complies with CRAN policy, I agree this is inconvenient.

My understanding is that it is allowed to have `require(package)` statements in examples **if** that `package` is listed as a `Suggests`.

My proposed fix is to check if all suggested packages are installed as part of the unit tests.  If not installed, the tests will then download the packages.  This will at least resolve the issue for developers who want to test upstream package dependencies.

**Comment by hadley** [comment]
I'd rather it just fail than it attempt to change my system while running tests.

R-exts has "Packages used to run examples or tests conditionally (e.g. via if(require(pkgname))) should be listed in ‘Suggests’ or ‘Enhances’. (This allows checkers to ensure that all the packages needed for a complete check are installed.)".  Which is sufficiently vague that it can be used to support either my position or your position

**Comment by hadley** [comment]
It's not a big deal if you choose not to do anything - the only (small) disadvantage is that I can't give you a heads up if something I've change in my package breaks something in your package. You'll still find out when CRAN runs its checks.

**Comment by andrie** [comment]
I will implement this using `skip()` if suggested packages are not installed.
