### ISSUE TITLE
margin not working for dendro_data.rpart

### ISSUE THREAD

**Issue by LluisRamon** [andrie/ggdendro#22]
Hi Andrie, 

First of all thanks for your package. I'm enjoying it a lot.

I would like to report that __margin__ parameter in __dendro_data.rpart__ does nothing. In the code it seems that temp1 and temp2 are defined but never used again.

A workarround is to change margins using ggplot2 xlim. If it is the correct way to adapt margins,  maybe you should remove this parameter and its documentation. 

A reproducible example:

```{r}
library("car")
data("Highway1")

library("rpart")
tree_model <- rpart(rate ~ ., data = Highway1)

ggtree <- dendro_data(tree_model)
ggtreeMargin <- dendro_data(tree_model, margin = 10)

all.equal(ggtree, ggtreeMargin)
```

**Comment by andrie** [comment]
Thank you for this report.

I have made the change in the dev branch
