### ISSUE TITLE
Not showing labels

### ISSUE THREAD

**Issue by seagatejiayilu** [andrie/ggdendro#23]
Hi Andrie,

I use ClustOfVar to get a fit, then I plot it with your great package.

**fit = ClustOfVar::hclustvar(X.quanti = D)
p1 = ggdendrogram(as.dendrogram(fit))**

The problem is: I have five laptops, three of them can show greatly with labels but two of them just cannot display the labels. What do you think might be causing the issue? Can it be Java issues? Thanks.

**Comment by andrie** [comment]
Two requests:

1. Can you please make the example reproducible so I can try it?
2. What are the Operating system and R version for the machines?

**Comment by andrie** [comment]
I have a suspicion this is related to #24.

A change in the `scales` package causes labels to display in `scales` v0.3, but not to display in `scales` 0.4.

I have now fixed the problem in `ggdendrogram()`, so hopefully this also resolves this issue.

@seagatejiayilu, Can you please report the version of `scales` that you have installed on these machines?

**Comment by xfim** [comment]
Same here, with scales_0.4.0 labels are not plotted. When using the development version it works.

**Comment by jiayi9** [comment]
http://stackoverflow.com/questions/36883291/r-package-ggdendro-plotting-labels-disppear

The version of scales is 0.3.0.

**Comment by andrie** [comment]
This was fixed with #24
