### ISSUE TITLE
Add scale as legend?

### ISSUE THREAD

**Issue by rhart604** [andrie/ggdendro#30]
Any way to display the scale?  I see there's a scales slot in the object but I can't figure out how to display it.

**Comment by andrie** [comment]
If you use `ggdendrogram()` to create your plot, the resulting object is a `ggplot`.  You have full control over this using any function in `ggplot()`.

Here are two solutions:

``` r
library(ggdendro)
library(ggplot2)

hc <- hclust(dist(USArrests), "ave")

# Use a different theme
ggdendrogram(hc, rotate = FALSE, size = 2) +
  theme_bw()
```

![](https://i.imgur.com/yN4j5Cr.png)

``` r

# Modify the theme only for the y axis
ggdendrogram(hc, rotate = FALSE, size = 2) +
  scale_alpha_continuous() +
  theme(
    axis.line.y = element_line()
  )
```

![](https://i.imgur.com/FOGLedl.png)

<sup>Created on 2023-09-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
