### ISSUE TITLE
Cannot set axis.line limit correctly

### ISSUE THREAD

**Issue by jernest1** [andrie/ggdendro#32]
I would like a y axis line with tick marks beside the dendrogram. It should start at 0 and end at the y max, similar to the base plotting behavior. However, nothing I've tried works. The line runs past the y limits I set. Running a little past the y max is ok (as the base example does) but I would really like it to start at 0. How can I make this work?
```
hc <- hclust(dist(mtcars))
```
```
# Base example
plot(hc)
```
![image](https://user-images.githubusercontent.com/13725669/136129683-6d5dc3c0-e9b5-413b-8a79-5708fbce0e6e.png)
```
# ggdendrogram
ggdendrogram(hc) + 
  coord_cartesian(ylim = c(0, max(hc$height))) +
  theme(
    axis.line.y = element_line(),
    axis.ticks = element_line()
  )
```
![image](https://user-images.githubusercontent.com/13725669/136129754-53032650-adad-4cc1-902b-cfc4ca3f3742.png)

**Comment by jernest1** [comment]
@talgalili I don't have a preference as long as it's ggplot. If there's an easy way to add an axis line to a dendrogram similar to base plot using dendextend please let me know. In this case I'm asking specifically about ggdendro.

**Comment by talgalili** [comment]
I'm not sure I follow, you show an example of how you've done it with code.
Is that solution not good for you? Are you looking for another solution?

**Comment by jernest1** [comment]
@talgalili I want the y axis to end at 0 like the base plot example. Notice how with ggdendro the y axis runs past 0.
