### ISSUE TITLE
Coloring the clusters?

### ISSUE THREAD

**Issue by Jeffrothschild** [andrie/ggdendro#33]
Hi Andrie,

Is it possible to allow the labels to be colored based on the clusters (using a certain number of cuts)? I was able to [make this work ](https://github.com/Jeffrothschild/correlation-visuals/blob/master/Example%20colored%20dendrogram.png) using dendextend::cutree() and then joining it to a dendro_data$labels tibble. 

It would be great to somehow use the dendro_data$segments output to select the number of cuts, which could allow you to color them accordingly.

Thanks!

**Comment by andrie** [comment]
I'm glad you can make this work using `dendextend`, and I suggest you keep using that package.  Unless somebody provides a pull request on `ggdendro`, it's unlikely that your request will ever make it into this package.

**Comment by talgalili** [comment]
Thanks Andrie for the comment.

Just quick FYI for anyone coming through this thread: it's already possible to combine dendextend colors with ggplot2 via the ggdend object.

```
library(dendextend)
# Create a complex dend:
dend <- iris[1:30, -5] %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  set("branches_k_color", k = 3) %>%
  set("branches_lwd", c(1.5, 1, 1.5)) %>%
  set("branches_lty", c(1, 1, 3, 1, 1, 2)) %>%
  set("labels_colors") %>%
  set("labels_cex", c(.9, 1.2))
# # plot the dend in usual "base" plotting engine:
# plot(dend)
# Now let's do it in ggplot2 :)
ggd1 <- as.ggdend(dend)
library(ggplot2)
ggplot(ggd1) # reproducing the above plot in ggplot2 :)
```

![image](https://github.com/user-attachments/assets/443e1fe7-5c24-4e11-ac5a-fa78d536f44c)
